### ISSUE TITLE
Documentation of known issues

### ISSUE THREAD

**Issue by yocheah** [yocheah/Fluxnet-Ameriflux#6]
Known issues in Dec FLUXNET 2015 release.
- On Ameriflux, we need to know what has changed between April 2016 release and December release
- Also list of data issues: such as aggregation, etc in December 2015 data.

**Comment by yocheah** [comment]
List of bugs under finalization by Carlo and Alessio

**Comment by daagarwal** [comment]
Megha assigned to this task because I want him to help create a design

**Comment by daagarwal** [comment]
Design is high priority
